#!/usr/bin/env bash
# shell script to copy file from local to remote server
if [[ "$#" -lt 3 ]]; then
	printf "%s\n" "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit;
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi;

