#!/usr/bin/env bash
# install nginx server
# added new html file
# make / to request index.html

apt-get update
apt-get install -y nginx

ROOT_LOCATION="/usr/share/nginx/html/";

rm -rf "$ROOT_LOCATION/index.html";

echo "Hello World!" > "$ROOT_LOCATION/index.html"
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
