#!/usr/bin/env bash
# nginx permission fix
# change the port to 8080
killall nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -H -u nginx bash -c service nginx start
