#!/usr/bin/env bash
# fix container in 7 lines or less
sudo pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
